# coding: utf-8

"""
    eLabFTW REST API v2 Documentation

    This document describes all available endpoints and methods for eLabFTW's API version 2.   # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import elabapi_python
from elabapi_python.models.team_tags_body1 import TeamTagsBody1  # noqa: E501
from elabapi_python.rest import ApiException


class TestTeamTagsBody1(unittest.TestCase):
    """TeamTagsBody1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamTagsBody1(self):
        """Test TeamTagsBody1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = elabapi_python.models.team_tags_body1.TeamTagsBody1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
