#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class gradient_based:
    fluent_name = ...
    child_names = ...
    postprocess_options = ...
    monitors = ...
    methods = ...
    calculation = ...
    observables = ...
    command_names = ...

    def enable(self, ):
        """
        Enables and loads adjoint module.
        """

