#
# This is an auto-generated file.  DO NOT EDIT!
#


from typing import Union, List, Tuple

class overset_child:
    fluent_name = ...
    child_names = ...
    name = ...
    phase = ...
    geom_disable = ...
    geom_dir_spec = ...
    geom_dir_x = ...
    geom_dir_y = ...
    geom_dir_z = ...
    geom_levels = ...
    geom_bgthread = ...
    query_names = ...

    def adjacent_cell_zone(self, ):
        """
        Get adjacent cell zone for this face zone.
        """

    def shadow_face_zone(self, ):
        """
        Get shadow zone for this wall zone.
        """

