from .rsc.tags.a import a
from .rsc.tags.body import body
from .rsc.tags.div import div
from .rsc.tags.head import head
from .rsc.tags.div import div
from .rsc.tags.html import html
from .rsc.tags.input_text import input_text
from .rsc.tags.link import link
from .rsc.tags.span import span
from .rsc.tags.title import title
