"""
    Delphix DCT API

    Delphix DCT API  # noqa: E501

    The version of the OpenAPI document: 3.9.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.algorithm_revision import AlgorithmRevision
from delphix.api.gateway.model.paginated_response_metadata import PaginatedResponseMetadata
globals()['AlgorithmRevision'] = AlgorithmRevision
globals()['PaginatedResponseMetadata'] = PaginatedResponseMetadata
from delphix.api.gateway.model.search_algorithm_revisions_response import SearchAlgorithmRevisionsResponse


class TestSearchAlgorithmRevisionsResponse(unittest.TestCase):
    """SearchAlgorithmRevisionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchAlgorithmRevisionsResponse(self):
        """Test SearchAlgorithmRevisionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchAlgorithmRevisionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
