season = "2022-23"

team_names_men = ["Calcit Volley",
                "FužinarSijMetalRavne",
                "HišaNaKolesihTriglav",
                "Salonit Anhovo",
                "ACH Volley Ljubljana",
                "Črnuče",
                "Merkur Maribor",
                "Panvita Pomgrad"]
team_names_women = ["Calcit Volley",
                    "Nova KBM Branik",
                    "ATK Grosuplje",
                    "GEN-I Volley",
                    "OD Krim",
                    "Ankaran",
                    "SIP Šempeter",
                    "Formis"]
team_names = team_names_men + team_names_women

teams_men = {
    "Calcit Volley" : {"1": "Planinšič Uroš",
                       "2": "Mujanović Nik",
                       "5": "Vinkovič Dino",
                       "6": "Lazar Luka",
                       "8": "Klobučar Jan",
                       "10": "Košenina Alan",
                       "11": "Arsenoski Miloš",
                       "12": "Okroglič Jure",
                       "13": "Sosa Luis",
                       "15": "Mitrašinović Tomislav",
                       "23": "Aponza Daniel",
                       "77": "Pavlovič Uroš"},
    "FužinarSijMetalRavne": {"1": "Cafuta Miha",
                             "3": "Lednik Nace",
                             "4": "Križanič Bor",
                             "5": "Knuplež Jani",
                             "6": "Ranc David",
                             "7": "Bregar Miha",
                             "9": "Erpič Uroš",
                             "10": "Makaš Emir",
                             "11": "Levar Uroš",
                             "12": "Hribernik Žiga",
                             "14": "Vučetić Luka",
                             "16": "Libnik Blaž",
                             "17": "Plesec Vasja",
                             "18": "Kasnik Jure",
                             "19": "Jelić Nemanja",
                             "23": "Ranc Vid"},
    "HišaNaKolesihTriglav": {"1": "Ibrišimovič Gal",
                             "4": "Nanut Maj",
                             "5": "Glamočanin Jure",
                             "6": "Tučen Uroš",
                             "7": "Fajfar Matic",
                             "9": "Rotar Bor Jese",
                             "11": "Snedec Amadej",
                             "12": "Šikanič Aljoša",
                             "13": "Mali Miha",
                             "14": "Adžović Adi",
                             "15": "Jovović Đorđe"},
    "Salonit Anhovo": {"1": "Kodrič Erik",
                       "2": "Stojanovič Aleksander",
                       "3": "Šarić Danijel",
                       "5": "Hesselholt Joachim",
                       "6": "Karnel Irenej",
                       "7": "Jeklin Primož",
                       "8": "Godnič Jani",
                       "9": "Kavčič Jakob",
                       "10": "Maretič Lian Svit",
                       "11": "Bojić Slobodan",
                       "12": "Okroglič Grega",
                       "13": "Kovačič Aleks",
                       "14": "Ikhbayri Mohamed",
                       "15": "Vrtovec Matic",
                       "17": "Maksimović Marko"},
    "ACH Volley Ljubljana": {"1": "Mejal Primož",
                             "4": "Satler Rok",
                             "5": "Šket Alen",
                             "8": "Mašulović Nemanja",
                             "9": "Todorović Vuk",
                             "10": "Bošnjak Črtomir",
                             "11": "Koncilja Danijel",
                             "12": "Šestan Filip",
                             "13": "Kovačič Jani",
                             "14": "Gjorgiev Nikola",
                             "17": "Videčnik Matic",
                             "18": "Kök Matej",
                             "19": "Šen Klemen"},
    "Črnuče": {"1": "Kržič Jošt",
               "2": "Mihelčič Gregor",
               "4": "Elikan Gaj",
               "5": "Prevorčnik Jaka",
               "6": "Karadža Pevc Matevž",
               "7": "Gornik Aljaž",
               "8": "Verdinek Jožef",
               "9": "Rojnik Matic",
               "10": "Oman Jurij",
               "11": "Sešek Jaka",
               "13": "Marovt Luka",
               "15": "Jančič Jan Karl",
               "16": "Valenčič Martin",
               "17": "Vilar Blaž",
               "19": "Ramšak Vid",
               "33": "Česnovar Matic"},
    "Merkur Maribor": {"2": "Jevšnik Jaka",
                       "3": "Vodušek Timotej",
                       "4": "Pernuš Gregor",
                       "5": "Adžović Sani",
                       "6": "McConnell Connor",
                       "8": "Bračko Rok",
                       "9": "Kumer Žiga",
                       "10": "Kržič Janž Janez",
                       "11": "Donik Žiga",
                       "12": "Leva Filip",
                       "13": "Fink Miha",
                       "14": "Najdič Nejc",
                       "16": "Iršič Jaka",
                       "21": "Toplišek Maj",
                       "42": "Peruničić Nemanja"},
    "Panvita Pomgrad": {"1": "Rajnar Urban",
                        "5": "Šormaz Nenad",
                        "6": "Avšič Tine",
                        "7": "Drvarič Urban",
                        "8": "Vrabl Tin",
                        "9": "Suhadolnik Vid",
                        "10": "Rojnik Jakob",
                        "11": "Kovačič Tit",
                        "12": "Legen Nik",
                        "13": "Milovanović Marko",
                        "14": "Bedrač Žan",
                        "15": "Fužir Urban",
                        "16": "Novak David",
                        "17": "Jurić Petar"},
}

teams_women = {
    "ATK Grosuplje": {"2": "Gorjup Ula",
                      "3": "Gojković Nadja",
                      "6": "Krašovec Zala",
                      "8": "Boben Rusić Zoja",
                      "9": "Šen Asja",
                      "10": "Kukman Naja",
                      "11": "Žužek Lana",
                      "12": "Pucelj Nika",
                      "13": "Filipič Tara",
                      "14": "Gornjec Hodnik Ajda",
                      "15": "Čož Klavdija",
                      "17": "Križman Kaja"},
    "GEN-I Volley": {"3": "Damjanović Sanja",
                     "4": "Frelih Polona",
                     "5": "Pertens Silvia",
                     "6": "Marušič Polona",
                     "9": "Rituper Lara",
                     "10": "Jelina Ula",
                     "11": "Blažič Pia",
                     "12": "Marušič Špela",
                     "13": "Makuc Gaja",
                     "15": "Mazej Anja",
                     "16": "Mohorič Julija",
                     "17": "Žigon Ana"},
    "OD Krim": {"1": "Mohorič Katjuša",
                "4": "Friškovec Tara",
                "5": "Zalokar Iza",
                "6": "Čotar Nika",
                "8": "Križnik Daša",
                "9": "Jovanović Maja",
                "10": "Kranjec Neja",
                "13": "Đukić Sara",
                "15": "Bogataj Laura",
                "16": "Jerman Alja",
                "18": "Janjić Maša",
                "61": "Belič Pia"},
    "Ankaran": {"2": "Kolenc Lajris",
                "3": "Jamnik Pregl Nika",
                "4": "Grbas Mia",
                "5": "Labinjan Živa",
                "6": "Kovačič Maja",
                "7": "Grudina Tina",
                "8": "Forštnarič Maja",
                "9": "Žnidar Anastazija",
                "10": "Valencic Sara",
                "11": "Cerovac Tara",
                "14": "Pangerc Ema",
                "17": "Kaker Tina"},
    "Calcit Volley": {"2": "Griljc Živa",
                      "7": "Radišković Andjelka",
                      "8": "Stojiljković Nina",
                      "9": "Vovk Ana Marija",
                      "10": "Đorđević Mila",
                      "12": "Boisa Naja",
                      "13": "Kregar Klara",
                      "14": "Charuk Lucille June",
                      "15": "Sillah Fatoumatta",
                      "16": "Vukojević Adriana",
                      "18": "Pucelj Maša",
                      "19": "Čižman Neja",
                      "20": "Banko Katja"},
    "Nova KBM Branik": {"1": "Mlakar Iza",
                        "2": "Milošič Klara",
                        "3": "Pogačar Eva",
                        "7": "Štampar Ronja",
                        "8": "Klajžar Daša",
                        "9": "Lekše Tali",
                        "11": "Senekovič Pia",
                        "12": "Cikač Urška",
                        "13": "Farkaš Anja",
                        "16": "Potokar Monika",
                        "17": "Lorber Fijok Lorena",
                        "18": "Kranjc Ana Mojca"},
    "SIP Šempeter": {"2": "Lukman Lina",
                     "3": "Božič Maša",
                     "4": "Koren Tia",
                     "5": "Črnila Vita",
                     "7": "Vovk Anja",
                     "8": "Bavdaž Nika",
                     "9": "Vidali Neja",
                     "10": "Mašulović Nataša",
                     "14": "Lebič Maja",
                     "17": "Kadunc Ira"},
    "Formis": {"3": "Vodušek Tjana",
               "4": "Škoflek Adela",
               "5": "Cvetko Daša",
               "7": "Šteharnik Tinkara",
               "8": "Zupan Lana",
               "9": "Godec Žana",
               "10": "Uršič Urša",
               "12": "Grubišič Čabo Julija",
               "13": "Milošič Nika",
               "14": "Divjak Naja",
               "16": "Klavžar Ema",
               "18": "Halužan Sagadin Žana",
               "21": "Bračič Neja"}
}
