def html_start():
    return ''.join([ '<style>',
                     'p { ',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',

def html_end():
    return ''.join([ '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',

