# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import maxpanda_python_sdk
from maxpanda_python_sdk.api.part_category_api import PartCategoryApi  # noqa: E501
from maxpanda_python_sdk.rest import ApiException


class TestPartCategoryApi(unittest.TestCase):
    """PartCategoryApi unit test stubs"""

    def setUp(self):
        self.api = PartCategoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_part_category_create(self):
        """Test case for part_category_create

        Create a new Part Category  # noqa: E501
        """
        pass

    def test_part_category_delete_part_category(self):
        """Test case for part_category_delete_part_category

        Delete PartCategory of Part  # noqa: E501
        """
        pass

    def test_part_category_get(self):
        """Test case for part_category_get

        Get a paged list of PartCategory  # noqa: E501
        """
        pass

    def test_part_category_get_0(self):
        """Test case for part_category_get_0

        Get a specific Part Category record  # noqa: E501
        """
        pass

    def test_part_category_put(self):
        """Test case for part_category_put

        Update an existing Part Category  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
