
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-15T21:01:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7430f25f771a50dc63ae17093b517a53f3dfae7f",
 "version": "2.9.10.post0.dev15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
