# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Task(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'site_ref': 'list[SiteRef]',
        'task_template_id': 'int',
        'name': 'str',
        'priority_ref': 'TaskPriorityRef',
        'description': 'str',
        'task_field_ref': 'list[TaskFieldRef]'
    }

    attribute_map = {
        'site_ref': 'SiteRef',
        'task_template_id': 'TaskTemplateId',
        'name': 'Name',
        'priority_ref': 'PriorityRef',
        'description': 'Description',
        'task_field_ref': 'TaskFieldRef'
    }

    def __init__(self, site_ref=None, task_template_id=None, name=None, priority_ref=None, description=None, task_field_ref=None):  # noqa: E501
        """Task - a model defined in Swagger"""  # noqa: E501
        self._site_ref = None
        self._task_template_id = None
        self._name = None
        self._priority_ref = None
        self._description = None
        self._task_field_ref = None
        self.discriminator = None
        if site_ref is not None:
            self.site_ref = site_ref
        if task_template_id is not None:
            self.task_template_id = task_template_id
        if name is not None:
            self.name = name
        if priority_ref is not None:
            self.priority_ref = priority_ref
        if description is not None:
            self.description = description
        if task_field_ref is not None:
            self.task_field_ref = task_field_ref

    @property
    def site_ref(self):
        """Gets the site_ref of this Task.  # noqa: E501


        :return: The site_ref of this Task.  # noqa: E501
        :rtype: list[SiteRef]
        """
        return self._site_ref

    @site_ref.setter
    def site_ref(self, site_ref):
        """Sets the site_ref of this Task.


        :param site_ref: The site_ref of this Task.  # noqa: E501
        :type: list[SiteRef]
        """

        self._site_ref = site_ref

    @property
    def task_template_id(self):
        """Gets the task_template_id of this Task.  # noqa: E501


        :return: The task_template_id of this Task.  # noqa: E501
        :rtype: int
        """
        return self._task_template_id

    @task_template_id.setter
    def task_template_id(self, task_template_id):
        """Sets the task_template_id of this Task.


        :param task_template_id: The task_template_id of this Task.  # noqa: E501
        :type: int
        """

        self._task_template_id = task_template_id

    @property
    def name(self):
        """Gets the name of this Task.  # noqa: E501


        :return: The name of this Task.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Task.


        :param name: The name of this Task.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def priority_ref(self):
        """Gets the priority_ref of this Task.  # noqa: E501


        :return: The priority_ref of this Task.  # noqa: E501
        :rtype: TaskPriorityRef
        """
        return self._priority_ref

    @priority_ref.setter
    def priority_ref(self, priority_ref):
        """Sets the priority_ref of this Task.


        :param priority_ref: The priority_ref of this Task.  # noqa: E501
        :type: TaskPriorityRef
        """

        self._priority_ref = priority_ref

    @property
    def description(self):
        """Gets the description of this Task.  # noqa: E501


        :return: The description of this Task.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Task.


        :param description: The description of this Task.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def task_field_ref(self):
        """Gets the task_field_ref of this Task.  # noqa: E501


        :return: The task_field_ref of this Task.  # noqa: E501
        :rtype: list[TaskFieldRef]
        """
        return self._task_field_ref

    @task_field_ref.setter
    def task_field_ref(self, task_field_ref):
        """Sets the task_field_ref of this Task.


        :param task_field_ref: The task_field_ref of this Task.  # noqa: E501
        :type: list[TaskFieldRef]
        """

        self._task_field_ref = task_field_ref

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Task, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Task):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
