from filesignaturecollectors.controller import CollectorController
from filesignaturecollectors.get_data_from_gck import GCKFileSignatures
from filesignaturecollectors.get_data_from_wiki import WikiFileSignatures
from filesignaturecollectors.to_sqlite3 import ToSqlite3
from filesignaturecollectors.to_file import ToFile
from filesignaturecollectors.models import FileMagicData
from filesignaturecollectors.utils.listfilemagicdata import ListFileMagicData
