# Generated by Django 5.0.2 on 2024-02-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='place_of_birth',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
