# Generated by Django 5.0.2 on 2024-02-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_application_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='updated_at',
        ),
    ]
