# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import maxpanda_python_sdk
from maxpanda_python_sdk.models.update_customer_model import UpdateCustomerModel  # noqa: E501
from maxpanda_python_sdk.rest import ApiException


class TestUpdateCustomerModel(unittest.TestCase):
    """UpdateCustomerModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateCustomerModel(self):
        """Test UpdateCustomerModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = maxpanda_python_sdk.models.update_customer_model.UpdateCustomerModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
