# Generated by Django 3.2.14 on 2022-09-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0007_add_natural_indexing'),
        ('extras', '0034_alter_fileattachment_mimetype'),
        ('nautobot_evpn', '0002_auto_20220901_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VLANVRF',
            new_name='VRFPrimaryVLAN',
        ),
    ]
