# Generated by Django 3.2.14 on 2022-09-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_evpn', '0003_rename_vlanvrf_vrfprimaryvlan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ethernetsegment',
            options={'verbose_name': 'Ethernet Segment', 'verbose_name_plural': 'Ethernet Segments'},
        ),
        migrations.AlterModelOptions(
            name='ethernetsegmentmembership',
            options={'verbose_name': 'Ethernet Segment Membership', 'verbose_name_plural': 'Ethernet Segment Memberships'},
        ),
        migrations.AlterModelOptions(
            name='vlanvrflist',
            options={'verbose_name': 'VLAN-To-VRF-Attachment', 'verbose_name_plural': 'VLAN-To-VRF-Attachments'},
        ),
        migrations.AlterModelOptions(
            name='vrfprimaryvlan',
            options={'verbose_name': 'VRF Primary VLAN', 'verbose_name_plural': 'VRF Primary VLANs'},
        ),
    ]
