# Generated by Django 3.2.16 on 2022-12-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0008_prefix_vlan_vlangroup_location'),
        ('nautobot_evpn', '0006_auto_20221214_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anycastdummyip',
            name='ip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anycastdummyip', to='ipam.ipaddress'),
        ),
        migrations.AlterField(
            model_name='anycastdummyip',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anycastdummyip', to='ipam.vlan'),
        ),
        migrations.AlterField(
            model_name='anycastip',
            name='ip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anycastip', to='ipam.ipaddress'),
        ),
        migrations.AlterField(
            model_name='anycastip',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anycastip', to='ipam.vlan'),
        ),
        migrations.AlterField(
            model_name='vlanvrflist',
            name='vlan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vlanvrflist', to='ipam.vlan'),
        ),
        migrations.AlterField(
            model_name='vlanvrflist',
            name='vrf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlanvrflist', to='ipam.vrf'),
        ),
        migrations.AlterField(
            model_name='vrfprimaryvlan',
            name='vlan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vrfprimaryvlan', to='ipam.vlan'),
        ),
        migrations.AlterField(
            model_name='vrfprimaryvlan',
            name='vrf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vrfprimaryvlan', to='ipam.vrf'),
        ),
    ]
