from typing import List, Self

class Poteau:
    def __init__(self, disks: List[int], id: int) -> None: ...
    @classmethod
    def createFromABC(cls, abc_notation: str, id: int) -> "Poteau": ...
    @property
    def isEmpty(self) -> bool: ...
    @property
    def size(self) -> int: ...
    @property
    def sizeOfLastDisk(self) -> int | None: ...
    def popLastDisk(self) -> int | None: ...
    def getDisks(self) -> List[int]: ...
    def pushDisk(self, size_of_disk: int) -> bool: ...
    def moveTo(self, poteau: Self) -> bool: ...
    def checkMove(self, poteau_destination: Self) -> bool: ...
