from amsdal_utils.errors import AmsdalError


class AmsdalRuntimeError(AmsdalError): ...


class TransactionNotFoundError(AmsdalError): ...


class AmsdalAuthenticationError(AmsdalRuntimeError): ...


class AmsdalDeployError(AmsdalRuntimeError): ...


class AmsdalMissingCredentialsError(AmsdalAuthenticationError): ...


class AmsdalAuthConnectionError(AmsdalAuthenticationError): ...


class AmsdalSignupError(AmsdalAuthenticationError): ...
