
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-17T01:06:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c04f69daec9e6195a2532e8e0b5d6cb236b2d08d",
 "version": "1.21.1.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
