# Generated by Django 5.0.2 on 2024-02-19 05:14

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_applicant_place_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='passport_photo',
            field=models.FileField(upload_to='documents/', validators=[api.validators.validate_passport_photo]),
        ),
    ]
