
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-16T14:15:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fab38eb32e1f6c84f3aa29e5878e5b3bfd20ca85",
 "version": "0.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
