import os

ENV_WATSONX_ASSISTANT_APIKEY='WATSONX_ASSISTANT_APIKEY'

ENV_WATSONX_ASSISTANT_ID="WATSONX_ASSISTANT_ID"

WATSONX_ASSISTANT_VERSION="2020-04-01"

WATSONX_ASSISTANT_SERVICE_URL="https://api.us-south.assistant.watson.cloud.ibm.com"