# Generated by Django 3.2.23 on 2024-02-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='名称')),
                ('memo', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('avatar', models.URLField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '帐号',
                'verbose_name_plural': '帐号',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='网址')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='instantid.account', verbose_name='帐号')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'ordering': ('-create_time',),
            },
        ),
    ]
