# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import maxpanda_python_sdk
from maxpanda_python_sdk.api.bins_api import BinsApi  # noqa: E501
from maxpanda_python_sdk.rest import ApiException


class TestBinsApi(unittest.TestCase):
    """BinsApi unit test stubs"""

    def setUp(self):
        self.api = BinsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bin_get(self):
        """Test case for bin_get

        Get list of Bins  # noqa: E501
        """
        pass

    def test_bin_get_0(self):
        """Test case for bin_get_0

        Get a specific Bin  # noqa: E501
        """
        pass

    def test_bin_post(self):
        """Test case for bin_post

        Create a Bin  # noqa: E501
        """
        pass

    def test_bin_put(self):
        """Test case for bin_put

        Update a Bin  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
