# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import maxpanda_python_sdk
from maxpanda_python_sdk.models.task_priority import TaskPriority  # noqa: E501
from maxpanda_python_sdk.rest import ApiException


class TestTaskPriority(unittest.TestCase):
    """TaskPriority unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskPriority(self):
        """Test TaskPriority"""
        # FIXME: construct object with mandatory attributes with example values
        # model = maxpanda_python_sdk.models.task_priority.TaskPriority()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
