
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-17T18:07:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "49f1e50ad7289a697594acdbd388d4eb1c9a722b",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
