# Generated by Django 5.0.2 on 2024-02-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_partner", "0001_initial"),
        ("artd_product", "0003_alter_product_brand"),
        ("artd_shopify", "0005_shopifyapicredential_category_regular_expression"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shipify Brand Name.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "artd_partner",
                    models.ForeignKey(
                        help_text="ArtD Partner associated with this category.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_partner.partner",
                        verbose_name="artd partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipify Brand",
                "verbose_name_plural": "Shipify Brands",
            },
        ),
        migrations.CreateModel(
            name="ShopifyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shopify Category Name.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "artd_partner",
                    models.ForeignKey(
                        help_text="ArtD Partner associated with this category.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_partner.partner",
                        verbose_name="artd partner",
                    ),
                ),
                (
                    "artd_tax",
                    models.ForeignKey(
                        blank=True,
                        help_text="ArtD Tax associated with this category.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_product.tax",
                        verbose_name="artd tax",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify Category",
                "verbose_name_plural": "Shopify Categories",
            },
        ),
    ]
