# Generated by Django 5.0.2 on 2024-02-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_partner", "0001_initial"),
        ("artd_shopify", "0008_shopifyproduct_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyGraphQlCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        help_text="Shopify Vendor.",
                        max_length=100,
                        verbose_name="Vendor",
                    ),
                ),
                (
                    "store_key",
                    models.CharField(
                        help_text="Shopify Store Key.",
                        max_length=255,
                        verbose_name="store key",
                    ),
                ),
                (
                    "api_version",
                    models.CharField(
                        help_text="Shopify API Version.",
                        max_length=255,
                        verbose_name="API version",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="Shopify API Key.",
                        max_length=255,
                        verbose_name="API key",
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        help_text="Shopify API Secret.",
                        max_length=255,
                        verbose_name="API secret",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True,
                        help_text="Shopify Access Token.",
                        null=True,
                        verbose_name="access token",
                    ),
                ),
                (
                    "product_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Shopify Product Counter.",
                        verbose_name="product counter",
                    ),
                ),
                (
                    "brand_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Shopify Brand Prefix.",
                        max_length=255,
                        null=True,
                        verbose_name="brand prefix",
                    ),
                ),
                (
                    "category_regular_expression",
                    models.CharField(
                        blank=True,
                        help_text="Shopify Category Regular Expression.",
                        max_length=255,
                        null=True,
                        verbose_name="category regular expression",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        help_text="Partner associated with this credential.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_partner.partner",
                        verbose_name="partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify GraphQl Credential",
                "verbose_name_plural": "Shopify GraphQl Credentials",
            },
        ),
    ]
