# Generated by Django 5.0.2 on 2024-02-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_shopify", "0009_shopifygraphqlcredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopifycategory",
            name="json_data",
            field=models.JSONField(
                default=dict,
                help_text="Shopify Category JSON Data.",
                verbose_name="json data",
            ),
        ),
    ]
