# Generated by Django 5.0.1 on 2024-02-16 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_partner", "0001_initial"),
        ("artd_product", "0006_image_remove_productimage_alt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the partner",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="artd_partner.partner",
                verbose_name="Partner",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="source",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Enter the source of the image",
                null=True,
                verbose_name="Source",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="status",
            field=models.BooleanField(default=True, verbose_name="status"),
        ),
    ]
