# Generated by Django 5.0.1 on 2024-02-18 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artd_partner', '0001_initial'),
        ('artd_product', '0009_product_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupedproduct',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Select the partner', null=True, on_delete=django.db.models.deletion.CASCADE, to='artd_partner.partner', verbose_name='Partner'),
        ),
    ]
