class ExeTestEnvVars:
    """
    Environment variables used to configure exeteest decorators
    """

    USE_EXE = 'EXETEST_USE_EXE'
    REBASE = 'EXETEST_REBASE'
    COMPARE_ONLY = 'EXETEST_COMPARE_ONLY'
    VERBOSE = 'EXETEST_VERBOSE'
    KEEP_OUTPUT_ON_SUCCESS = 'EXETEST_KEEP_OUTPUT_ON_SUCCESS'
    NUM_DIFFS = 'EXETEST_NUM_DIFFS'
    EXETEST_DIFF_EXE = 'EXETEST_DIFF_EXE'
    NO_RUN = 'EXETEST_NO_RUN'
    DISABLE_SKIP = 'EXETEST_DISABLE_SKIP'
    FILE_FILTER = 'EXETEST_FILE_FILTER'
