# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import maxpanda_python_sdk
from maxpanda_python_sdk.models.vendor_detail import VendorDetail  # noqa: E501
from maxpanda_python_sdk.rest import ApiException


class TestVendorDetail(unittest.TestCase):
    """VendorDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVendorDetail(self):
        """Test VendorDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = maxpanda_python_sdk.models.vendor_detail.VendorDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
