# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateInvoiceItemModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'invoice_item_type_id': 'int',
        'invoice_item_type_name': 'str',
        'description': 'str',
        'unit_price': 'float',
        'quantity': 'float'
    }

    attribute_map = {
        'invoice_item_type_id': 'InvoiceItemTypeId',
        'invoice_item_type_name': 'InvoiceItemTypeName',
        'description': 'Description',
        'unit_price': 'UnitPrice',
        'quantity': 'Quantity'
    }

    def __init__(self, invoice_item_type_id=None, invoice_item_type_name=None, description=None, unit_price=None, quantity=None):  # noqa: E501
        """CreateInvoiceItemModel - a model defined in Swagger"""  # noqa: E501
        self._invoice_item_type_id = None
        self._invoice_item_type_name = None
        self._description = None
        self._unit_price = None
        self._quantity = None
        self.discriminator = None
        self.invoice_item_type_id = invoice_item_type_id
        self.invoice_item_type_name = invoice_item_type_name
        if description is not None:
            self.description = description
        if unit_price is not None:
            self.unit_price = unit_price
        if quantity is not None:
            self.quantity = quantity

    @property
    def invoice_item_type_id(self):
        """Gets the invoice_item_type_id of this CreateInvoiceItemModel.  # noqa: E501


        :return: The invoice_item_type_id of this CreateInvoiceItemModel.  # noqa: E501
        :rtype: int
        """
        return self._invoice_item_type_id

    @invoice_item_type_id.setter
    def invoice_item_type_id(self, invoice_item_type_id):
        """Sets the invoice_item_type_id of this CreateInvoiceItemModel.


        :param invoice_item_type_id: The invoice_item_type_id of this CreateInvoiceItemModel.  # noqa: E501
        :type: int
        """
        if invoice_item_type_id is None:
            raise ValueError("Invalid value for `invoice_item_type_id`, must not be `None`")  # noqa: E501

        self._invoice_item_type_id = invoice_item_type_id

    @property
    def invoice_item_type_name(self):
        """Gets the invoice_item_type_name of this CreateInvoiceItemModel.  # noqa: E501


        :return: The invoice_item_type_name of this CreateInvoiceItemModel.  # noqa: E501
        :rtype: str
        """
        return self._invoice_item_type_name

    @invoice_item_type_name.setter
    def invoice_item_type_name(self, invoice_item_type_name):
        """Sets the invoice_item_type_name of this CreateInvoiceItemModel.


        :param invoice_item_type_name: The invoice_item_type_name of this CreateInvoiceItemModel.  # noqa: E501
        :type: str
        """
        if invoice_item_type_name is None:
            raise ValueError("Invalid value for `invoice_item_type_name`, must not be `None`")  # noqa: E501

        self._invoice_item_type_name = invoice_item_type_name

    @property
    def description(self):
        """Gets the description of this CreateInvoiceItemModel.  # noqa: E501


        :return: The description of this CreateInvoiceItemModel.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateInvoiceItemModel.


        :param description: The description of this CreateInvoiceItemModel.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def unit_price(self):
        """Gets the unit_price of this CreateInvoiceItemModel.  # noqa: E501


        :return: The unit_price of this CreateInvoiceItemModel.  # noqa: E501
        :rtype: float
        """
        return self._unit_price

    @unit_price.setter
    def unit_price(self, unit_price):
        """Sets the unit_price of this CreateInvoiceItemModel.


        :param unit_price: The unit_price of this CreateInvoiceItemModel.  # noqa: E501
        :type: float
        """

        self._unit_price = unit_price

    @property
    def quantity(self):
        """Gets the quantity of this CreateInvoiceItemModel.  # noqa: E501


        :return: The quantity of this CreateInvoiceItemModel.  # noqa: E501
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this CreateInvoiceItemModel.


        :param quantity: The quantity of this CreateInvoiceItemModel.  # noqa: E501
        :type: float
        """

        self._quantity = quantity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateInvoiceItemModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateInvoiceItemModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
