# Generated by Django 5.0.1 on 2024-02-18 14:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_word', '0002_worddocumentpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddocumentpage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
