# Generated by Django 5.0.2 on 2024-02-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artd_partner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopfyProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="Shopify Product ID.",
                        max_length=255,
                        verbose_name="product id",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        default=dict,
                        help_text="Shopify Product JSON Data.",
                        verbose_name="json data",
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this product is processed or not.",
                        verbose_name="processed",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Partner associated with this product.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_partner.partner",
                        verbose_name="partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopfy Product",
                "verbose_name_plural": "Shopfy Products",
            },
        ),
        migrations.CreateModel(
            name="ShopifyApiCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        help_text="Shopify Vendor.",
                        max_length=100,
                        verbose_name="Vendor",
                    ),
                ),
                (
                    "store_key",
                    models.CharField(
                        help_text="Shopify Store Key.",
                        max_length=255,
                        verbose_name="store key",
                    ),
                ),
                (
                    "api_version",
                    models.CharField(
                        help_text="Shopify API Version.",
                        max_length=255,
                        verbose_name="API version",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True,
                        help_text="Shopify Access Token.",
                        null=True,
                        verbose_name="access token",
                    ),
                ),
                (
                    "product_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Shopify Product Counter.",
                        verbose_name="product counter",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        help_text="Partner associated with this credential.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_partner.partner",
                        verbose_name="partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify API Credential",
                "verbose_name_plural": "Shopify API Credentials",
            },
        ),
        migrations.CreateModel(
            name="ShopifyAppCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active or not.",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        help_text="Shopify Vendor.",
                        max_length=100,
                        verbose_name="vendor",
                    ),
                ),
                (
                    "api_version",
                    models.CharField(
                        help_text="Shopify API Version.",
                        max_length=255,
                        verbose_name="API version",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="Shopify API Key.",
                        max_length=255,
                        verbose_name="API key",
                    ),
                ),
                (
                    "api_password",
                    models.CharField(
                        help_text="Shopify API Password.",
                        max_length=255,
                        verbose_name="API password",
                    ),
                ),
                (
                    "store_url",
                    models.CharField(
                        help_text="Shopify Store URL.",
                        max_length=255,
                        verbose_name="store URL",
                    ),
                ),
                (
                    "callback_url",
                    models.URLField(
                        help_text="Shopify Callback URL.", verbose_name="callback URL"
                    ),
                ),
                (
                    "auth_url",
                    models.TextField(
                        blank=True,
                        help_text="Shopify Auth URL.",
                        null=True,
                        verbose_name="auth URL",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True,
                        help_text="Shopify Access Token.",
                        null=True,
                        verbose_name="access token",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        help_text="Partner associated with this credential.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_partner.partner",
                        verbose_name="partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify Credential",
                "verbose_name_plural": "Shopify Credentials",
            },
        ),
    ]
