# Generated by Django 5.0.2 on 2024-02-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_shopify", "0003_shopifyproduct_brand_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopifyproduct",
            name="brand_prefix",
        ),
        migrations.AddField(
            model_name="shopifyapicredential",
            name="brand_prefix",
            field=models.CharField(
                blank=True,
                help_text="Shopify Brand Prefix.",
                max_length=255,
                null=True,
                verbose_name="brand prefix",
            ),
        ),
    ]
