# Generated by Django 5.0.2 on 2024-02-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_shopify", "0006_shopifybrand_shopifycategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shopifybrand",
            options={
                "verbose_name": "Shopify Brand",
                "verbose_name_plural": "Shopify Brands",
            },
        ),
        migrations.AlterField(
            model_name="shopifybrand",
            name="name",
            field=models.CharField(
                help_text="Shopify Brand Name.", max_length=255, verbose_name="name"
            ),
        ),
    ]
