# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import maxpanda_python_sdk
from maxpanda_python_sdk.models.vendor_create_update_response_model import VendorCreateUpdateResponseModel  # noqa: E501
from maxpanda_python_sdk.rest import ApiException


class TestVendorCreateUpdateResponseModel(unittest.TestCase):
    """VendorCreateUpdateResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVendorCreateUpdateResponseModel(self):
        """Test VendorCreateUpdateResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = maxpanda_python_sdk.models.vendor_create_update_response_model.VendorCreateUpdateResponseModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
