
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-19T14:54:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "526655eb84613662ca622f9a1fcceb13acd7bbdc",
 "version": "8.4.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
