# coding: utf-8

"""
    DataForSEO API documentation

    DataForSEO API is the starting point on your journey towards building powerful SEO software. With DataForSEO you can get all the data you need to build an efficient application while also saving your time and budget. DataForSEO API is using the REST technology for interchanging data between your application and our service. The data exchange is made through the widely used HTTP protocol, which allows applying our API to almost all programming languages.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.appendix_backlinks_limits_rates_data_info import AppendixBacklinksLimitsRatesDataInfo

class TestAppendixBacklinksLimitsRatesDataInfo(unittest.TestCase):
    """AppendixBacklinksLimitsRatesDataInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppendixBacklinksLimitsRatesDataInfo:
        """Test AppendixBacklinksLimitsRatesDataInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppendixBacklinksLimitsRatesDataInfo`
        """
        model = AppendixBacklinksLimitsRatesDataInfo()
        if include_optional:
            return AppendixBacklinksLimitsRatesDataInfo(
                summary = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                history = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                content_duplicates = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                domain_intersection = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                backlinks = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                domain_pages = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                anchors = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                referring_domains = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                page_intersection = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                referring_networks = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                bulk_ranks = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                bulk_backlinks = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                bulk_new_lost_backlinks = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                bulk_new_lost_referring_domains = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                bulk_referring_domains = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                errors = 1.337,
                domain_pages_summary = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                timeseries_summary = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                timeseries_new_lost_summary = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, ),
                competitors = openapi_client.models.appendix_bing_keywords_data_day_limits_rates_data_info.AppendixBingKeywordsDataDayLimitsRatesDataInfo(
                    live = 1.337, )
            )
        else:
            return AppendixBacklinksLimitsRatesDataInfo(
        )
        """

    def testAppendixBacklinksLimitsRatesDataInfo(self):
        """Test AppendixBacklinksLimitsRatesDataInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
