# coding: utf-8

"""
    DataForSEO API documentation

    DataForSEO API is the starting point on your journey towards building powerful SEO software. With DataForSEO you can get all the data you need to build an efficient application while also saving your time and budget. DataForSEO API is using the REST technology for interchanging data between your application and our service. The data exchange is made through the widely used HTTP protocol, which allows applying our API to almost all programming languages.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_amazon_reviews_task_get_advanced_task import MerchantAmazonReviewsTaskGetAdvancedTask

class TestMerchantAmazonReviewsTaskGetAdvancedTask(unittest.TestCase):
    """MerchantAmazonReviewsTaskGetAdvancedTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantAmazonReviewsTaskGetAdvancedTask:
        """Test MerchantAmazonReviewsTaskGetAdvancedTask
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantAmazonReviewsTaskGetAdvancedTask`
        """
        model = MerchantAmazonReviewsTaskGetAdvancedTask()
        if include_optional:
            return MerchantAmazonReviewsTaskGetAdvancedTask(
                id = '',
                status_code = 56,
                status_message = '',
                time = '',
                cost = 1.337,
                result_count = 56,
                path = [
                    ''
                    ],
                data = openapi_client.models.data.data(),
                result = [
                    openapi_client.models.merchant_amazon_reviews_task_get_advanced_result.MerchantAmazonReviewsTaskGetAdvancedResult(
                        asin = '', 
                        type = '', 
                        se_domain = '', 
                        location_code = 56, 
                        language_code = '', 
                        check_url = '', 
                        datetime = '', 
                        spell = openapi_client.models.spell_info.SpellInfo(
                            keyword = '', 
                            type = '', ), 
                        title = '', 
                        image = openapi_client.models.images_element.ImagesElement(
                            type = '', 
                            alt = '', 
                            url = '', 
                            image_url = '', ), 
                        rating = openapi_client.models.rating_element.RatingElement(
                            type = '', 
                            position = '', 
                            rating_type = '', 
                            value = '', 
                            votes_count = 56, 
                            rating_max = 56, ), 
                        reviews_count = 56, 
                        item_types = [
                            ''
                            ], 
                        items_count = 56, 
                        items = [
                            openapi_client.models.amazon_base_serp_element_item.AmazonBaseSerpElementItem(
                                se_type = '', )
                            ], )
                    ]
            )
        else:
            return MerchantAmazonReviewsTaskGetAdvancedTask(
        )
        """

    def testMerchantAmazonReviewsTaskGetAdvancedTask(self):
        """Test MerchantAmazonReviewsTaskGetAdvancedTask"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
