VERSION_YEAR = 2024
VERSION_MONTH = int('02')
VERSION_DAY = int('20')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('00')
MAJOR_VERSION = 0
MINOR_VERSION = 12
PATCH_VERSION = 202402201100
version_date = '2024/02/20 11:00'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
