from numpy import ndarray

def generate_primes(start: int = 0, end: int) -> ndarray[int]: ...

def generate_n_primes(start: int = 0, n: int) -> ndarray[int]: ...

def get_nth_prime(start: int = 0, n: int) -> int: ...

def count_primes(start: int = 0, end: int) -> int: ...

def count_twins(start: int = 0, end: int) -> int: ...

def count_triplets(start: int = 0, end: int) -> int: ...

def count_sextuplets(start: int = 0, end: int) -> int: ...

def count_quadruplets(start: int = 0, end: int) -> int: ...

def count_quintuplets(start: int = 0, end: int) -> int: ...

def get_max_stop() -> int: ...

def is_prime(number) -> bool: ...