# Autogenerated by devscripts/update-version.py

__version__ = '2024.02.17.232706'

RELEASE_GIT_HEAD = '974d444039c8bbffb57265c6792cd52d169fe1b9'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.02.17.232706dev'
